name: React CI CD Workflow
on: 
  workflow_dispatch:
  push:
    branches:
     - Github_Actions_Hands-on

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 20
      
      - name: Install dependencies and build app
        run: |
          npm ci 
          npm run build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-artifact-build
          path: ./dist

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository in test job
        uses: actions/checkout@v6

      - name: Setup Node.js environment in test job
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
  
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-artifact-build
          path: dist

      - name: Run Unit Tests for app
        run: npm test -- --watchAll=false
        
      - name: Validate Build Output
        run: |
          test -f dist/index.html
          echo "Build file exists"
   
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-artifact-build
          path: dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Debug Docker user
        run: docker info

      - name: Debug username
        run: echo "USER=${{ vars.DOCKERHUB_USERNAME }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: aagash11/github_actions_docker:latest
          platforms: linux/amd64,linux/arm64
      
      - name: Verify Docker Image
        run: |
          docker pull aagash11/github_actions_docker:latest
          echo "Docker image pulled successfully"

  deploy:
    needs: deploy-to-dockerhub
    runs-on: ubuntu-latest

    env:
      API_URL: ${{ github.ref == 'refs/heads/Github_Actions_Hands-on' && 'https://api.dev.com' || 'https://api.prod.com' }}
      DB_NAME: ${{ github.ref == 'refs/heads/Github_Actions_Hands-on' && 'dev_db' || 'prod_db' }}

    steps:
      - name: Print Deployment Info
        run: |
          echo "Deploying application..."
          echo "Branch: ${{ github.ref }}"
          echo "API_URL=$API_URL"
          echo "DB_NAME=$DB_NAME"